### PR TITLE
Brazilian Translation

### PR DESCRIPTION
**Pull request by flexevolved**

### CODE REVIEW

**Comment by PichotM** [comment]
btw i do not believe GTA V makes the distinction between PR/BR
So it might appear later if this is accepted

**Comment by flexevolved** [comment]
This can be used to pt-pt, i translate this beacuse many of my friends, portugueses and brazilians as so confused with the semi-translation for portuguese

**Comment by PichotM** [comment]
The new version should support Portuguese and Brazilians portuguese if your system is using BR

**Comment by PichotM** [comment]
Thanks for the PR

**Pull request merged**
